# Generated by Django 3.1.5 on 2021-03-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('service_provider_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('posted_by', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
