# Generated by Django 3.1.5 on 2021-03-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('answer', models.TextField(max_length=500)),
                ('posted_by', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_category', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('question', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('posted_by', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
