# Generated by Django 3.1.5 on 2021-03-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0003_answer_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
