# Generated by Django 3.1.5 on 2021-03-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0004_remove_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
